# Generated by Django 3.2.9 on 2021-11-13 08:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название группы')),
                ('user_coordintator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to=settings.AUTH_USER_MODEL)),
                ('users_volonter', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Необходимо ввести номер телефона в формате: +70123456789, допускается до 15 знаков', regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер организации')),
                ('email', models.EmailField(max_length=200, verbose_name='Почта')),
                ('personal', models.CharField(max_length=64, verbose_name='Сотрудник организации')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('colicestvo', models.IntegerField(verbose_name='Количество')),
                ('ves', models.FloatField(verbose_name='вес')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('srok', models.DateField(verbose_name='Срок годности')),
                ('desc', models.TextField(blank=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='mainapp.group')),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ', to='mainapp.organ')),
            ],
        ),
    ]
