# Generated by Django 3.2.9 on 2021-11-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='users',
            new_name='users_volonter',
        ),
    ]
