# Generated by Django 3.2.9 on 2021-11-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='who_you',
            new_name='status',
        ),
    ]
