# Generated by Django 3.2.9 on 2021-11-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_rename_who_you_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Подтверждён'),
        ),
    ]
